### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by yaunsine** [EdisonLeeeee/MaskGAE#5]
pardon, sir, could u tell me how to download the dataset about  "~/public_data/pyg_data"?

**Comment by EdisonLeeeee** [comment]
Sorry, `~/public_data/pyg_data` is the root path that specifies the dataset folder. You can change it to something like `./`(current folder or directory). All the datasets will be automatically downloaded to this folder.

**Comment by yaunsine** [comment]
thx
