### ISSUE TITLE
About the performance on graph classification

### ISSUE THREAD

**Issue by cxw-droid** [EdisonLeeeee/MaskGAE#6]
Hi, Thank you for the interesting paper! In the paper, the experiments do not include a performance comparison on graph classification task. Is there any reason for this? Thanks.

**Comment by EdisonLeeeee** [comment]
Hi

Thank you for your interest. As mentioned in the paper, GAEs are essentially contrastive learning models that aim to maximize the mutual information between paired subgraph views associated with a connected edge. However, in many graph-level datasets, the graphs are often small and much more sparse. Applying masking techniques to these graph structures can significantly limit the propagation of messages between nodes, though it can still achieve a decent performance.

As a result, MaskGAE is more suitable for node-level tasks and, more specifically, link-level tasks.
